# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d974dd4043d15bb76365579f1d238fd44eee84caba99aef014403d639d9838039ebfd7121b0dff3f89e2aad9b89d59a8b2fe3a318dc3d79e03416502ca3c5cf2

test:
  secret_key_base: 01050dd5a152374f2b448932b304e52e88845efc15e50986afd5814d357c2b277b9a65e6314614b49284f002148e191c1f2050634faa0d98a4d6b09ec3e1027d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
